services:
  nhxinfobot:
    build: .
    container_name: nhxinfobot
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    volumes:
      - nhx_repo:/opt/nhxinfobot
      - ${HOME}/configs/nhxinfobot/config.json:/config/config.json:ro

volumes:
  nhx_repo:
